Fin/Fin/Models/Cost.cs
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Cost
    {
        public ObjectId Id { get; set; }
        public ObjectId UserId { get; set; }

        [Required(ErrorMessage = "* Введите дату в формате dd.mm.yyyy;")]
        [RegularExpression(@"[0-9]{2}.[0-9]{2}.[0-9]{4}", ErrorMessage = "Некорректная дата")]
        public string date { get; set; }

        [Required(ErrorMessage = "* Введите количество (руб)")]
        [Range(typeof(int), "0", "100000000")]
        public string Count { get; set; }

        public string Comment { get; set; }
        public string Category { get; set; }
    }
}

Fin/Fin/Controllers/CostController.cs
using Fin.Models;
using Models;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.CRUD;
using WebApplication1.Models;
using WebApplication1.Rep;

namespace Fin.Controllers
{
    public class CostController : Controller
    {
        User u;
        public ActionResult Cost(string user, string id)
        {
            try {
                MongoUser mu = new MongoUser();
                u = mu.GetById(new ObjectId(user));
                string s = Session["status"] as string;
                if (s == u.Login)
                {
                    u.Costs = new MongoCost().Select(u.Id);
                    BigUserCostModel big = new BigUserCostModel();
                    big.user = u;
                    big.user.Costs = new MongoCost().Select(new ObjectId(user));

                    big.cost = new WebApplication1.Models.Cost();





                    return View(big);
                }
                else
                    if (s == "null")
                    return RedirectToAction("Index", "Home");
                else
                {
                    u = mu.GetByLogin(s);
                    return RedirectToAction("Cost", "Cost", new { user = u.Id });
                }
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }

        }

        public ActionResult Logon()
        {
            u = null;
            Session["status"] = "null";
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Create(BigUserCostModel model, string categ)
        {
            
            if (ModelState.IsValid)
            {
                Cost cost = model.cost;
                MongoUser mu = new MongoUser();
                cost.UserId = mu.GetByLogin(model.user.Login).Id;
                MongoCost mi = new MongoCost();
                Category category = new Category();

                //income.Category=category.getICategory().IndexOf(income.Category).ToString();
                cost.Category = category.getCCategory().IndexOf(categ).ToString();
                mi.Create(cost);
                model.user = mu.GetByLogin(model.user.Login);
                model.user.CurrentMoney -= Int32.Parse(model.cost.Count);
                mu.Update(model.user);
                return RedirectToAction("Cost", "Cost", new { user = cost.UserId });
            }

            return RedirectToAction("Cost", "Cost", new { user = new MongoUser().GetByLogin(model.user.Login).Id });
           
        }


        public ActionResult Delete(string id, string userid)
        {
            MongoCost mi = new MongoCost();
            User user = new MongoUser().GetById(new ObjectId(userid));
            user.CurrentMoney += Int32.Parse(mi.GetById(new ObjectId(id)).Count);
            mi.DeleteById(new ObjectId(id));
            new MongoUser().Update(user);
            return RedirectToAction("Cost", "Cost", new { user = userid });
        }

        [HttpPost]
        public ActionResult Change(string id, string userid)
        {
            
            MongoCost mi = new MongoCost();
            MongoUser mu = new MongoUser();
            Cost cost = mi.GetById(new ObjectId(id));
            BigUserCostModel model = new BigUserCostModel();
            model.cost = cost;
            model.user = mu.GetById(cost.UserId);
            model.user.Costs = mi.Select(cost.UserId);
            return View(model);
        }

        [HttpPost]
        public ActionResult ChangeItem(BigUserCostModel model, string categ, string id)
        {
            Category category = new Category();
            MongoCost mi = new MongoCost();
            MongoUser mu = new MongoUser();
            model.cost.Category = category.getCCategory().IndexOf(categ).ToString();
            model.cost.UserId = new MongoUser().GetByLogin(model.user.Login).Id;
            model.cost.Id = new ObjectId(id);
            model.user = mu.GetByLogin(model.user.Login);
            model.user.CurrentMoney += Int32.Parse(mi.GetById(new ObjectId(id)).Count);
            model.user.CurrentMoney -= Int32.Parse(model.cost.Count);
            mu.Update(model.user);
            mi.Update(model.cost);

            // return View(big);
            return RedirectToAction("Cost", "Cost", new { user = model.cost.UserId });
        }
    }
}

Fin/Fin/Controllers/EditUserController.cs
using Models;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Account;
using WebApplication1.Models;
using WebApplication1.Rep;

namespace Fin.Controllers
{
    public class EditUserController : Controller
    {
        // GET: EditUser
        public ActionResult Index(string login)
        {
            try {
                return View(new Registr() { Login = login });
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult Commit(Registr model, string old)
        {
            if (ModelState.IsValid)
            {
                if (model.Login.Length < 3)
                {
                    ModelState.AddModelError("Login", "* Имя (логин) слишком короткое;");
                }
                else
                if (model.Password.Length < 5)
                {
                    ModelState.AddModelError("Password", "* Длина пароля не менее 5 символов;");
                }
                else
                {
                    
                    int status = Account.Change(model);

                    if (status != -1)
                    {
                        ObjectId id = new MongoUser().GetByLogin(model.Login).Id;
                        return RedirectToAction("Income", "Profile", new { user = id });
                    }
                    else
                        return View(model);
                }
            }
            return View(model);
        }
    }
}

Fin/Fin/Controllers/GraphicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fin.Models;
using Models;
using MongoDB.Bson;
using WebApplication1.CRUD;
using WebApplication1.Models;
using WebApplication1.Rep;

namespace Fin.Controllers
{
    public class GraphicController : Controller
    {
        // GET: Graphic
        public ActionResult Index(string user, string id)
        {
            User u;

            MongoUser mu = new MongoUser();
            try
            {
                u = mu.GetById(new ObjectId(user));
            }
            catch (Exception)
            {

                return RedirectToAction("Index", "Home");
            }


            string s = Session["status"] as string;

            if (s == u.Login)
            {
                u.Costs = new MongoCost().Select(u.Id);
                BigUserCIModel big = new BigUserCIModel();
                big.user = u;

                big.user.Costs = new MongoCost().Select(new ObjectId(user));
                big.user.Incomes = new MongoIncome().Select(new ObjectId(user));
                big.cost = new WebApplication1.Models.Cost();

                return View(big);
            }
            else
                if (s == "null")
                return RedirectToAction("Index", "Home");
            else
            {
                u = mu.GetByLogin(s);
                return RedirectToAction("Cost", "Cost", new { user = u.Id });
            }


            // ViewData["id"] = user;
            // return View();
        }
    }
}

Fin/Fin/Controllers/LogController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.CRUD;
using WebApplication1.Models;
using WebApplication1.Rep;

namespace Fin.Controllers
{
    public class LogController : Controller
    {        
        public ActionResult Index(string user)
        {
            try {
                LoggerModel lm = new LoggerModel();
                ViewData["id"] = user;
                return View(new List<LoggerModel>());
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult GetLog(string from, string to, string login)
        {
            try { 
            List<LoggerModel> list = new List<LoggerModel>();
            //ViewData["id"] = user;
            MongoIncome mi = new MongoIncome();
            MongoCost mc = new MongoCost();
            MongoUser mu = new MongoUser();
            User user = mu.getUserAndLists(login, from, to);
                list = BuildLoggerModel(user);

            int a=0, b=0;
            foreach (LoggerModel l in list)
            {
                if (l.Table == 0)
                    a += Int32.Parse(l.Count);
                else
                    b += Int32.Parse(l.Count);
            }
            ViewData["login"] = user.Login;
            ViewData["from"] = from;
            ViewData["to"] = to;
            ViewData["income"] = a;
            ViewData["cost"] = b;
            list.Sort(CompareDate);

                MakePdf("Отчет с " + from + " по " + to+'\n', "Доход: " + a + " руб; расход: " + b + " руб; баланс: " + (a + b).ToString() + " руб \n", list);          
            return View(list);
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public FileResult Pdf(IEnumerable<LoggerModel> model)
        {
            Stream stream = new FileStream(Request.PhysicalApplicationPath + "result.pdf", FileMode.Open);
            return File(stream, "application/zip", "result.pdf");

        }

//-----------------------------------------------------------------------
        private List<LoggerModel> BuildLoggerModel(User user)
        {
            List<LoggerModel> list = new List<LoggerModel>();
            foreach (Income i in user.Incomes)
            {
                LoggerModel lm = new LoggerModel();
                lm.Category = i.Category;
                lm.Comment = i.Comment;
                lm.Count = '+' + i.Count;
                lm.Date = i.date;
                lm.Table = 0;
                list.Add(lm);
            }

            foreach (Cost i in user.Costs)
            {
                LoggerModel lm = new LoggerModel();
                lm.Category = i.Category;
                lm.Comment = i.Comment;
                lm.Count = '-' + i.Count;
                lm.Date = i.date;
                lm.Table = 1;
                list.Add(lm);
            }
            return list;
        }
        static public int CompareDate(LoggerModel lm1, LoggerModel lm2)
        {
            string[] Alm1 = lm1.Date.Split('.');
            string[] Alm2 = lm2.Date.Split('.');
            //DateTime dt = new DateTime();
            
            return new DateTime(Int32.Parse(Alm1[2]),Int32.Parse(Alm1[1]),Int32.Parse(Alm1[0]))
                .CompareTo(new DateTime(Int32.Parse(Alm2[2]), Int32.Parse(Alm2[1]), Int32.Parse(Alm2[0])));
        }
        private void MakePdf(string Title, string all, List<LoggerModel> list)
        {
            Document document = new Document();
            Category c = new Category();
            PdfWriter writer = PdfWriter.GetInstance(document,new FileStream(Request.PhysicalApplicationPath+"result.pdf", FileMode.Create));
            document.Open();
            string fg = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Fonts), "ARIAL.TTF");
            BaseFont fgBaseFont = BaseFont.CreateFont(fg, BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED);

            iTextSharp.text.Font fgFont = new iTextSharp.text.Font(fgBaseFont, 20, iTextSharp.text.Font.BOLD, BaseColor.BLACK);
            Phrase p = new Phrase(Title,fgFont);
            document.Add(p);

            fgFont = new iTextSharp.text.Font(fgBaseFont, 16, iTextSharp.text.Font.NORMAL, BaseColor.BLACK);
            p = new Phrase(all, fgFont);
            document.Add(p);

            PdfPTable table = new PdfPTable(4);
            fgFont = new iTextSharp.text.Font(fgBaseFont, 12, iTextSharp.text.Font.NORMAL, BaseColor.BLACK);

            p = new Phrase("Количество", fgFont);
            PdfPCell  cell = new PdfPCell(p);
            cell.BorderWidth = 1;
            cell.Colspan = 1;
            cell.Rowspan = 1;
            table.AddCell(cell);

            p = new Phrase("Категория", fgFont);
            cell = new PdfPCell(p);
            cell.BorderWidth = 1;
            cell.Colspan = 1;
            cell.Rowspan = 1;
            table.AddCell(cell);

            p = new Phrase("Дата", fgFont);
            cell = new PdfPCell(p);
            cell.BorderWidth = 1;
            cell.Colspan = 1;
            cell.Rowspan = 1;
            table.AddCell(cell);

            p = new Phrase("Комментарий", fgFont);
            cell = new PdfPCell(p);
            cell.BorderWidth = 1;
            cell.Colspan = 1;
            cell.Rowspan = 1;
            table.AddCell(cell);

            foreach (LoggerModel lm in list)
            {
                p = new Phrase(lm.Count, fgFont);
                cell = new PdfPCell(p);
                cell.BorderWidth = 1;
                cell.Colspan = 1;
                cell.Rowspan = 1;
                table.AddCell(cell);

                if (lm.Table==0)
                    p = new Phrase(c.getICategory().ElementAt(Int32.Parse(lm.Category)), fgFont);
                else
                    p = new Phrase(c.getCCategory().ElementAt(Int32.Parse(lm.Category)), fgFont);
                cell = new PdfPCell(p);
                cell.BorderWidth = 1;
                cell.Colspan = 1;
                cell.Rowspan = 1;
                table.AddCell(cell);

                p = new Phrase(lm.Date, fgFont);
                cell = new PdfPCell(p);
                cell.BorderWidth = 1;
                cell.Colspan = 1;
                cell.Rowspan = 1;
                table.AddCell(cell);

                p = new Phrase(lm.Comment, fgFont);
                cell = new PdfPCell(p);
                cell.BorderWidth = 1;
                cell.Colspan = 1;
                cell.Rowspan = 1;
                table.AddCell(cell);
            }

            document.Add(table);
            document.Close();
            writer.Close();
        }        
    }
}

Fin/Fin/Views/Cost/Change.cshtml
@model Fin.Models.BigUserCostModel

@using WebApplication1.Models
@{

    Layout = "~/Views/Shared/_ProfileLayout.cshtml";
    Cost inc = new Cost();
    Models.Category c = new Models.Category();
    Model.cost.UserId = Model.user.Id;

}

<div id="menu">
    <ul>
        <li>@Html.ActionLink("Доходы", "Income", "Profile", new { user = Model.user.Id }, new { @class = "item" })</li>
        <li>@Html.ActionLink("Расходы", "Cost", "Cost", new { user = Model.user.Id }, new { @class = "choose" })</li>
        <li>@Html.ActionLink("Отчеты", "Index", "Log", new { user = Model.user.Id }, new { @class = "item" })</li>
        <li>@Html.ActionLink("Графики", "Index", "Graphic", new { user = Model.user.Id }, new { @class = "item" })</li>
    </ul>
</div>
<div class="profile">
    <h1>@Html.ValueFor(x => x.user.Login)</h1>    @Html.ActionLink(" ", "Index", "EditUser", new { login = Model.user.Login }, new { @class = "edit" })
    <h3>Текущий счет: @Html.ValueFor(x => x.user.CurrentMoney) руб</h3>    @Html.ActionLink(" ", "Logon", "Profile", new { area = "" }, new { @class = "home" })
</div>


<h6 style="position:absolute; left:50%; top:180px; width:224px;font-size:36px;margin-left:-112px;">Мои расходы</h6>
<div class="tabls">
    <table class="table" style="font-size:20px;">
        <tr>
            <td></td>
            <td>
                Количество
            </td>
            <td>
                Категория
            </td>
            <td>
                Дата траты
            </td>
            <td>
                Комментарий
            </td>
            <td style="width:120px"></td>

        </tr>

        @foreach (Cost i in Model.user.Costs)
        {
            <tr>
                <td>
                    <div style="background:url(../../image/gif-@i.Category-1.png) no-repeat; width:30px; height:30px"></div>
                </td>
                <td>
                    -@i.Count
                </td>
                <td>
                    @c.getCCategory().ElementAt(Int32.Parse(i.Category))

                </td>
                <td>
                    @i.date
                </td>
                <td>
                    @i.Comment
                </td>
                <td>
                    <div>
                        @using (Html.BeginForm("Change", "Cost", new { id = @i.Id, userid = @i.UserId }, FormMethod.Post))
                        {
                            <input type="submit" value="" style="border:none; width:30px; height:30px; background: url(../../image/pencil32.png); " />
                        }
                    </div>
                    <div style="margin-top:-36px; margin-left:40px;">
                        @using (Html.BeginForm("Delete", "Cost", new { id = @i.Id, userid = @i.UserId }, FormMethod.Post))
                        {
                            <input type="submit" value="" style="border:none; width:30px; height:30px; background: url(../../image/stop32.png); " />
                        }


                    </div>
                </td>
            </tr>
        }
    </table>

</div>
<div class="tablsedit">
    @using (Html.BeginForm("ChangeItem", "Cost", new { id = Model.cost.Id.ToString() }, FormMethod.Post))
    {
        <table>
            <tr>
                <td>
                    @Html.HiddenFor(x => x.user.Login)
                    @Html.TextBoxFor(x => x.cost.Count, null, new { @class = "form-control", placeholder = "Количество *", pattern = "[0-9]{0,15}", id = "inpus" })
                </td>
                <td>
                    <select id="inpus" name="categ" class="form-control">
                        @foreach (string ct in c.getCCategory())
                        {
                            if (@ct.CompareTo(@c.getCCategory().ElementAt(Int32.Parse(Model.cost.Category))) == 0)
                            {
                                <option selected>@ct</option>
                            }
                            else
                            {
                                <option>@ct</option>
                            }

                        }
                    </select>
                </td>
                <td>
                    <div class="input-group input-append date" id="datePicker">
                        @Html.TextBoxFor(x => x.cost.date, null, new
                   {
                       @class = "form-control",
                       name = "date",
                       placeholder = "Дата *",
                       id = "inpus2",
                       style = "top:5px; margin-right:0px;"
                   })
                </td>
                <td>
                    @Html.TextBoxFor(x => x.cost.Comment, null, new { @class = "form-control", placeholder = "Комментарий", id = "inpus", style = "width:350px; margin-left:30px; margin-right:0px;" })
                </td>
                <td>
                    <input type="submit" value="✓" style="font-size:68px; border:none; background-color:transparent; margin-left:12px" />
                </td>
            </tr>

            <tr>
                <td>
                    * Обязательные поля. <br> Дата в формате: dd.mm.yyy
                </td>
            </tr>
        </table>
    }
</div>

<script>
        $(document).ready(function () {
            var startDate = new Date('01.01.2012');
            var FromEndDate = new Date();
            var ToEndDate = new Date();
            ToEndDate.setDate(ToEndDate.getDate() + 365);

            $('#inpus2').datepicker({
                weekStart: 1,
                autoclose: true,
                format: 'dd.mm.yyyy'
            })
                .on('changeDate', function (selected) {
                    startDate = new Date(selected.date.valueOf());
                   // startDate.setDate(startDate.getDate(new Date(selected.date.valueOf())));
                    $('#inpus2').datepicker('setStartDate', startDate);
                });
        });
</script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>

Fin/Fin/Views/Cost/Cost.cshtml
@model Fin.Models.BigUserCostModel

@using WebApplication1.Models
@{
    ViewBag.Title = "Cost";
    Layout = "~/Views/Shared/_ProfileLayout.cshtml";
    Cost inc = new Cost();
    Models.Category c = new Models.Category();
    Model.cost.UserId = Model.user.Id;

}



<div id="menu">
    <ul>
        <li>@Html.ActionLink("Доходы", "Income", "Profile", new { user = Model.user.Id }, new { @class = "item" })</li>
        <li>@Html.ActionLink("Расходы", "Cost", "Cost", new { user = Model.user.Id }, new { @class = "choose" })</li>
        <li>@Html.ActionLink("Отчеты", "Index", "Log", new { user = Model.user.Id }, new { @class = "item" })</li>
        <li>@Html.ActionLink("Графики", "Index", "Graphic", new { user = Model.user.Id }, new { @class = "item" })</li>
    </ul>
</div>
<div class="profile">
    <h1>@Html.ValueFor(x => x.user.Login)</h1>    @Html.ActionLink(" ", "Index", "EditUser", new { login= Model.user.Login}, new { @class = "edit" })
    <h3>Текущий счет: @Html.ValueFor(x => x.user.CurrentMoney) руб</h3>    @Html.ActionLink(" ", "Logon", "Profile", new { area = "" }, new { @class = "home" })
</div>


<h6 style="position:absolute; left:50%; top:180px; width:224px;font-size:36px;margin-left:-112px;">Мои расходы</h6>
<div class="tabls">
    <table class="table" style="font-size:20px;">
        <tr>
            <td></td>
            <td>
                Количество
            </td>
            <td>
                Категория
            </td>
            <td>
                Дата поступления
            </td>
            <td>
                Комментарий
            </td>
            <td style="width:120px"></td>

        </tr>

        @foreach (Cost i in Model.user.Costs)
        {
            <tr>
                <td>
                    <div style="background: url(../image/gif-@i.Category-1.png) no-repeat; width:30px; height:30px"></div>
                </td>
                <td>
                    -@i.Count руб
                </td>
                <td>
                    @c.getCCategory().ElementAt(Int32.Parse(i.Category))

                </td>
                <td>
                    @i.date
                </td>
                <td>
                    @i.Comment
                </td>
                <td>
                    <div>
                        @using (Html.BeginForm("Change", "Cost", new { id = @i.Id.ToString(), userid = @i.UserId }, FormMethod.Post))
                        {
                            <input type="submit" value="" style="border:none; width:30px; height:30px; background: url(../image/pencil32.png);" />
                        }
                    </div>
                    <div style="margin-top:-36px; margin-left:40px;">
                        @using (Html.BeginForm("Delete", "Cost", new { id = @i.Id, userid = @i.UserId }, FormMethod.Post))
                        {
                            <input type="submit" value="" style="border:none; width:30px; height:30px; background: url(../image/stop32.png); " />
                        }


                    </div>
                </td>
            </tr>
        }
    </table>

</div>
<div class="tablsedit">
    @using (Html.BeginForm("Create", "Cost", FormMethod.Post))
    {
        <table>
            <tr>
                <td>
                    @Html.HiddenFor(x => x.user.Login)
                    @Html.TextBoxFor(x => x.cost.Count, null, new { @class = "form-control", placeholder = "Количество *", pattern = "[0-9]{0,15}", id = "inpus" })
                </td>
                <td>
                    <select id="inpus" name="categ" class="form-control">

                        @foreach (string ct in c.getCCategory())
                        {
                            <option>@ct</option>
                        }
                    </select>
                </td>
                <td>
                    
                    <div class="input-group input-append date" id="">
                        @Html.TextBoxFor(x => x.cost.date, null, new
                       {
                           @class = "form-control",
                           placeholder = "Дата ",
                           id = "inpus2",
                           style = "top:5px; margin-right:0px;"
                       })

                    </div>
</td>
                <td>
                    @Html.TextBoxFor(x => x.cost.Comment, null, new { @class = "form-control", placeholder = "Комментарий", id = "inpus", style = "width:350px; margin-left:30px; margin-right:0px;" })
                </td>
                <td>
                    <input type="submit" value="+" style="font-size:68px; border:none; background-color:transparent; margin-left:12px" />
                </td>
            </tr>

            <tr>
                <td>
                    * Обязательные поля. 
                </td>
            </tr>
        </table>
    }
</div>

<script>
        $(document).ready(function () {
            var startDate = new Date('01.01.2012');
            var FromEndDate = new Date();
            var ToEndDate = new Date();
            ToEndDate.setDate(ToEndDate.getDate() + 365);

            $('#inpus2').datepicker({
                weekStart: 1,                
                autoclose: true,
                format: 'dd.mm.yyyy'
            })
                .on('changeDate', function (selected) {
                    startDate = new Date(selected.date.valueOf());
                   // startDate.setDate(startDate.getDate(new Date(selected.date.valueOf())));
                   // $('#inpus').datepicker('setStartDate', startDate);
                });           
        });
</script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>