Fin/Fin/Models/Registr.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Models
{
    public class Registr
    {
        [Required(ErrorMessage = "* Введите имя (логин);")]
        public string Login { get; set; }

        [Required(ErrorMessage = "* Введите пароль;")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "* Повторите пароль;")]
        [Compare("Password", ErrorMessage = "Пароли не совпадают")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    }
}

Fin/Fin/Controllers/RegistrController.cs
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Account;

namespace Fin.Controllers
{
    public class RegistrController : Controller
    {
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Registr reg)
        {
            
            if (ModelState.IsValid)
            {
                if (reg.Login.Length < 3)
                {
                    ModelState.AddModelError("Login", "* Имя (логин) слишком короткое;");
                }
                else
                if (reg.Password.Length < 5)
                {
                    ModelState.AddModelError("Password", "* Длина пароля не менее 5 символов;");
                }
                else
                {
                    int status = Account.Change(reg);
                    if ( status == 0)
                        return RedirectToAction("Success");
                    else
                        if (status == 1)
                    {
                        ModelState.AddModelError("Login", "* Такой логин уже занят;");
                        return View(reg);
                    }
                    else
                        return RedirectToAction("Error");
                }
            }
            return View(reg);
        }

        public ActionResult Success()
        {
            return View();
        }

        public ActionResult Error()
        {
            return View();
        }


    }
}

Fin/Fin/Views/Registr/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/HomeLayout.cshtml";

}
@model Models.Registr
<div id="homelink">
    @Html.ActionLink("Регистрация", "Index", "Registr", new { area = "" }, new { @class = "links", @style = "color:white" })
    <b> / </b>
    @Html.ActionLink("Войти", "Index", "Home", new { area = "" }, new { @class = "links" })
</div>
@using (Html.BeginForm("Index", "Registr", FormMethod.Post))
{
    <div id="form">

        <table>
            <tr>
                <td>
                    <div id="label"><b>Регистрация</b><input type="submit" id="img" value=""/></div>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.TextBoxFor(x => x.Login, new { @class = "inputs", placeholder = "Введите имя (логин)"})                    
                </td>
            </tr>
            <tr>
                <td>
                    @Html.PasswordFor(x => x.Password, new { @class = "inputs", placeholder = "Введите пароль" })
                    
                </td>
            </tr>
            <tr>
                <td>
                    @Html.PasswordFor(x => x.ConfirmPassword, new { @class = "inputs", placeholder = "Повторите пароль", style="margin-bottom:30px"})
                   
                </td>
            </tr>
            <tr>
                <td>
                   @Html.ValidationMessageFor(model => model.Login, null, new { @class = "message" })<br />
                   @Html.ValidationMessageFor(model => model.Password, null, new { @class = "message" }) <br />
                   @Html.ValidationMessageFor(model => model.ConfirmPassword, null, new { @class = "message" })
                </td>
            </tr>
        </table>
       
    </div>
}

Fin/Fin/Views/Registr/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/HomeLayout.cshtml";
}
<div id="homelink">
    @Html.ActionLink("Регистрация", "Index", "Registr", new { area = "" }, new { @class = "links" })
    <b> / </b>
    @Html.ActionLink("Войти", "Index", "Home", new { area = "" }, new { @class = "links", @style = "color:white" })
</div>
<div style="position:absolute;top:40px; left:100px; color:green">
    <h2>Регистрация прошла успешно! <br>Вы можете войти в систему.</h2>
</div>